const swaggerJSDoc = require('swagger-jsdoc');
const { SWAGGER_NEWS_AGGREGATION_ENGINE_SERVICE_URL } = require('../config/environment');

const options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'News Aggregation Engine API',
            version: '1.0.0',
            description: 'API for send personalized news preferences via email, Generated by AI',
        },
        servers: [
            {
                url: SWAGGER_NEWS_AGGREGATION_ENGINE_SERVICE_URL,
            },
        ],
    },
    apis: ['./src/routes/*.js'],
};

const swaggerSpec = swaggerJSDoc(options);

module.exports = swaggerSpec;